package com.muzamil.propertyreturnfiler;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.net.URLEncoder;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private final int BLUE=Color.rgb(64,151,249), BLUE2=Color.rgb(27,20,243), INK=Color.rgb(8,7,25), BG=Color.rgb(244,246,250), MUTED=Color.rgb(113,109,136), LINE=Color.rgb(229,232,240), GREEN=Color.rgb(30,158,99), RED=Color.rgb(225,73,73), ORANGE=Color.rgb(245,166,35);
    private DBHelper db; private LinearLayout root, body; private String active="home"; private long activeClientId=0;

    @Override public void onCreate(Bundle b){super.onCreate(b);db=new DBHelper(this);if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},101);showSplash();}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);if(i!=null&&"reminders".equals(i.getStringExtra("open")))showReminders();}

    private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density);}
    private GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private GradientDrawable stroke(int color,int radius,int strokeColor){GradientDrawable g=shape(color,radius);g.setStroke(dp(1),strokeColor);return g;}
    private GradientDrawable gradient(int c1,int c2,int radius){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{c1,c2});g.setCornerRadius(dp(radius));return g;}
    private TextView text(String s,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(s==null?"":s);t.setTextSize(sp);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);t.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));t.setPadding(0,dp(3),0,dp(3));return t;}
    private Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(shape(Color.WHITE,22));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));c.setLayoutParams(p);c.setElevation(dp(1));return c;}
    private TextView iconText(String label,int icon,int size,int color){TextView t=text(label,size,color,false);t.setCompoundDrawablesWithIntrinsicBounds(icon,0,0,0);t.setCompoundDrawablePadding(dp(8));return t;}
    private Button pill(String label,int icon,boolean primary){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(14);b.setGravity(Gravity.CENTER);b.setTextColor(primary?Color.WHITE:INK);b.setCompoundDrawablesWithIntrinsicBounds(icon,0,0,0);b.setCompoundDrawablePadding(dp(8));b.setBackground(shape(primary?BLUE2:Color.WHITE,22));b.setPadding(dp(14),0,dp(14),0);b.setElevation(primary?dp(2):0);return b;}
    private TextView title(String s){TextView t=text(s,18,INK,true);t.setPadding(0,dp(12),0,dp(10));return t;}

    private void showSplash(){
        LinearLayout s=new LinearLayout(this);s.setOrientation(LinearLayout.VERTICAL);s.setGravity(Gravity.CENTER);s.setPadding(dp(30),dp(30),dp(30),dp(30));s.setBackground(gradient(Color.rgb(235,245,255),Color.WHITE,0));
        ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.ic_app);logo.setBackground(shape(Color.WHITE,28));logo.setPadding(dp(10),dp(10),dp(10),dp(10));logo.setElevation(dp(8));s.addView(logo,new LinearLayout.LayoutParams(dp(112),dp(112)));
        TextView n=text("Muzamil Abbas",18,MUTED,true);n.setGravity(Gravity.CENTER);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-1,-2);np.setMargins(0,dp(24),0,0);s.addView(n,np);
        TextView h=text("Property Return Filer",30,INK,true);h.setGravity(Gravity.CENTER);s.addView(h);
        TextView sub=text("Client ERP • FBR • Smart Reminders",14,MUTED,false);sub.setGravity(Gravity.CENTER);s.addView(sub);
        setContentView(s);new android.os.Handler().postDelayed(()->showHome(),850);
    }

    private void shell(String screen,String subtitle){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(16),dp(12),dp(16),dp(8));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);
        LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);tt.addView(text(screen,26,INK,true));tt.addView(text(subtitle,12,MUTED,false));top.addView(tt,new LinearLayout.LayoutParams(0,-2,1));
        TextView bell=iconCircle(R.drawable.ic_bell);bell.setOnClickListener(v->showReminders());top.addView(bell,new LinearLayout.LayoutParams(dp(44),dp(44)));root.addView(top);
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,dp(12),0,dp(80));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));root.addView(bottomNav());setContentView(root);
    }
    private TextView iconCircle(int icon){TextView t=new TextView(this);t.setGravity(Gravity.CENTER);t.setCompoundDrawablesWithIntrinsicBounds(icon,0,0,0);t.setBackground(shape(Color.WHITE,22));t.setElevation(dp(1));return t;}
    private View bottomNav(){LinearLayout wrap=new LinearLayout(this);wrap.setGravity(Gravity.CENTER_VERTICAL);wrap.setPadding(dp(6),dp(5),dp(6),dp(5));wrap.setBackground(shape(Color.WHITE,28));wrap.setElevation(dp(8));String[] labs={"Home","Clients","Reminders","More"};int[] icons={R.drawable.ic_home,R.drawable.ic_people,R.drawable.ic_bell,R.drawable.ic_grid};String[] keys={"home","clients","reminders","more"};for(int i=0;i<labs.length;i++){final int x=i;LinearLayout item=new LinearLayout(this);item.setGravity(Gravity.CENTER);item.setOrientation(LinearLayout.VERTICAL);item.setPadding(dp(4),dp(4),dp(4),dp(3));if(active.equals(keys[i]))item.setBackground(shape(Color.rgb(237,244,255),20));ImageView im=new ImageView(this);im.setImageResource(icons[i]);im.setAlpha(active.equals(keys[i])?1f:.55f);item.addView(im,new LinearLayout.LayoutParams(dp(22),dp(22)));TextView l=text(labs[i],10,active.equals(keys[i])?BLUE2:MUTED,active.equals(keys[i]));l.setGravity(Gravity.CENTER);item.addView(l);item.setOnClickListener(v->{if(x==0)showHome();else if(x==1)showClients("");else if(x==2)showReminders();else showMore();});wrap.addView(item,new LinearLayout.LayoutParams(0,dp(58),1));}return wrap;}

    private void showHome(){active="home";shell("Return Filer","Muzamil Abbas Property Return Filer");
        LinearLayout hero=card();hero.setBackground(gradient(Color.rgb(126,190,255),Color.rgb(49,139,245),28));
        LinearLayout hr=new LinearLayout(this);hr.setGravity(Gravity.CENTER_VERTICAL);LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.addView(text("Client Control Center",13,Color.WHITE,false));ht.addView(text("Everything due, in one place.",24,Color.WHITE,true));hr.addView(ht,new LinearLayout.LayoutParams(0,-2,1));ImageView app=new ImageView(this);app.setImageResource(R.drawable.ic_app);app.setBackground(shape(Color.WHITE,18));app.setPadding(dp(6),dp(6),dp(6),dp(6));hr.addView(app,new LinearLayout.LayoutParams(dp(54),dp(54)));hero.addView(hr);hero.addView(gap(18));
        LinearLayout nums=new LinearLayout(this);nums.setOrientation(LinearLayout.HORIZONTAL);nums.addView(heroStat("Clients",db.countClients()+""),new LinearLayout.LayoutParams(0,dp(78),1));nums.addView(heroStat("Pending",db.countPending()+""),new LinearLayout.LayoutParams(0,dp(78),1));nums.addView(heroStat("Reminders",db.countReminders()+""),new LinearLayout.LayoutParams(0,dp(78),1));hero.addView(nums);body.addView(hero);

        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button add=pill("Add Client",R.drawable.ic_add,true);add.setOnClickListener(v->clientForm(null));actions.addView(add,new LinearLayout.LayoutParams(0,dp(58),1));Space sp=new Space(this);actions.addView(sp,new LinearLayout.LayoutParams(dp(10),1));Button rem=pill("Reminder",R.drawable.ic_bell,false);rem.setOnClickListener(v->reminderForm(0));actions.addView(rem,new LinearLayout.LayoutParams(0,dp(58),1));body.addView(actions);body.addView(gap(8));

        body.addView(title("Today at a glance"));LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.HORIZONTAL);stats.addView(statCard("Filed",db.countFiled()+"",GREEN),new LinearLayout.LayoutParams(0,dp(108),1));Space s1=new Space(this);stats.addView(s1,new LinearLayout.LayoutParams(dp(10),1));stats.addView(statCard("Need action",db.countPending()+"",RED),new LinearLayout.LayoutParams(0,dp(108),1));body.addView(stats);

        body.addView(title("Quick workspace"));LinearLayout g=new LinearLayout(this);g.setOrientation(LinearLayout.VERTICAL);quickRow(g,"FBR Filings","Monthly / annual filing records",R.drawable.ic_doc,()->showFilingsHub());quickRow(g,"Calendar & Due Dates","See upcoming work",R.drawable.ic_calendar,()->showCalendar());quickRow(g,"Payments","Track paid and pending fees",R.drawable.ic_payment,()->showPaymentsHub());quickRow(g,"Reports","Client and filing overview",R.drawable.ic_grid,()->showReports());body.addView(g);
        body.addView(title("Clients needing attention"));List<DBHelper.Client> cs=db.clients("");for(int i=0;i<Math.min(3,cs.size());i++)body.addView(clientMini(cs.get(i)));
    }
    private View heroStat(String l,String v){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);x.addView(text(v,24,Color.WHITE,true));TextView z=text(l,11,0xFFEAF4FF,false);z.setGravity(Gravity.CENTER);x.addView(z);return x;}
    private View statCard(String l,String v,int c){LinearLayout x=card();x.setGravity(Gravity.CENTER_VERTICAL);x.addView(text(v,26,c,true));x.addView(text(l,13,MUTED,false));return x;}
    private void quickRow(LinearLayout parent,String a,String b,int icon,Runnable r){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);TextView ic=iconCircle(icon);c.addView(ic,new LinearLayout.LayoutParams(dp(46),dp(46)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(12),0,0,0);tx.addView(text(a,15,INK,true));tx.addView(text(b,12,MUTED,false));c.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView go=text("›",28,MUTED,false);c.addView(go);c.setOnClickListener(v->r.run());parent.addView(c);}

    private View clientMini(DBHelper.Client c){LinearLayout box=card();box.setOrientation(LinearLayout.HORIZONTAL);box.setGravity(Gravity.CENTER_VERTICAL);TextView avatar=text(initials(c.name),15,Color.WHITE,true);avatar.setGravity(Gravity.CENTER);avatar.setBackground(gradient(BLUE,BLUE2,24));box.addView(avatar,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(12),0,0,0);tx.addView(text(c.name,15,INK,true));tx.addView(text(safe(c.taxType)+" • Due "+safe(c.nextDue),12,MUTED,false));box.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView go=text("›",26,MUTED,false);box.addView(go);box.setOnClickListener(v->clientProfile(c.id));return box;}

    private void showClients(String query){active="clients";shell("Clients","Search, add and manage every client");
        EditText search=new EditText(this);search.setHint("Search name, business, WhatsApp or NTN");search.setSingleLine(true);search.setText(query);search.setTextSize(14);search.setCompoundDrawablesWithIntrinsicBounds(R.drawable.ic_search,0,0,0);search.setCompoundDrawablePadding(dp(10));search.setPadding(dp(14),0,dp(12),0);search.setBackground(stroke(Color.WHITE,20,LINE));body.addView(search,new LinearLayout.LayoutParams(-1,dp(54)));
        Button add=pill("Add New Client",R.drawable.ic_add,true);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(56));ap.setMargins(0,dp(12),0,dp(10));body.addView(add,ap);add.setOnClickListener(v->clientForm(null));
        LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);renderClientList(list,query);
        search.setOnEditorActionListener((v,a,e)->{renderClientList(list,search.getText().toString());return true;});
        search.setOnFocusChangeListener((v,f)->{if(!f)renderClientList(list,search.getText().toString());});
    }
    private void renderClientList(LinearLayout list,String q){list.removeAllViews();List<DBHelper.Client> cs=db.clients(q);TextView count=text(cs.size()+" clients",13,MUTED,true);count.setPadding(0,dp(4),0,dp(10));list.addView(count);for(DBHelper.Client c:cs){LinearLayout box=card();box.setOrientation(LinearLayout.HORIZONTAL);box.setGravity(Gravity.CENTER_VERTICAL);TextView av=text(initials(c.name),15,Color.WHITE,true);av.setGravity(Gravity.CENTER);av.setBackground(gradient(BLUE,BLUE2,24));box.addView(av,new LinearLayout.LayoutParams(dp(50),dp(50)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(12),0,0,0);tx.addView(text(c.name,16,INK,true));tx.addView(text(safe(c.business),12,MUTED,false));tx.addView(text(safe(c.taxType)+"  •  "+safe(c.status),11,BLUE2,true));box.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView go=text("›",28,MUTED,false);box.addView(go);box.setOnClickListener(v->clientProfile(c.id));list.addView(box);}}

    private void clientProfile(long id){DBHelper.Client c=db.client(id);if(c==null){showClients("");return;}active="clients";activeClientId=id;shell(c.name,"Client profile • "+safe(c.taxType));
        LinearLayout p=card();p.setBackground(gradient(Color.rgb(232,244,255),Color.WHITE,26));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView av=text(initials(c.name),19,Color.WHITE,true);av.setGravity(Gravity.CENTER);av.setBackground(gradient(BLUE,BLUE2,30));top.addView(av,new LinearLayout.LayoutParams(dp(62),dp(62)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(14),0,0,0);tx.addView(text(c.name,21,INK,true));tx.addView(text(safe(c.business),13,MUTED,false));tx.addView(text(safe(c.status),12,GREEN,true));top.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView edit=iconCircle(R.drawable.ic_edit);edit.setOnClickListener(v->clientForm(c));top.addView(edit,new LinearLayout.LayoutParams(dp(44),dp(44)));p.addView(top);p.addView(gap(14));p.addView(infoLine("WhatsApp",safe(c.whatsapp)));p.addView(infoLine("NTN",safe(c.ntn)));p.addView(infoLine("CNIC",safe(c.cnic)));p.addView(infoLine("Next due",safe(c.nextDue)));body.addView(p);
        LinearLayout a=new LinearLayout(this);Button wa=pill("WhatsApp",R.drawable.ic_chat,true);wa.setOnClickListener(v->openWhatsApp(c));a.addView(wa,new LinearLayout.LayoutParams(0,dp(55),1));Space ss=new Space(this);a.addView(ss,new LinearLayout.LayoutParams(dp(10),1));Button rr=pill("Add Reminder",R.drawable.ic_bell,false);rr.setOnClickListener(v->reminderForm(c.id));a.addView(rr,new LinearLayout.LayoutParams(0,dp(55),1));body.addView(a);
        body.addView(title("FBR / Return filings"));List<DBHelper.Filing> fs=db.filings(id);if(fs.isEmpty())body.addView(emptyCard("No filing added yet."));for(DBHelper.Filing f:fs)body.addView(filingCard(id,f));Button af=pill("Add Filing Record",R.drawable.ic_add,true);af.setOnClickListener(v->filingForm(id));body.addView(af,new LinearLayout.LayoutParams(-1,dp(55)));
        body.addView(title("Client workspace"));quickRow(body,"Documents","Required / received records",R.drawable.ic_doc,()->showDocuments(id));quickRow(body,"Payments","Consultancy fee tracking",R.drawable.ic_payment,()->showPayments(id));quickRow(body,"Reminders","Client-specific follow-ups",R.drawable.ic_bell,()->showClientReminders(id));quickRow(body,"Notes & contact","Address, email and notes",R.drawable.ic_people,()->showClientNotes(c));
        Button del=pill("Delete Client",R.drawable.ic_people,false);del.setTextColor(RED);del.setOnClickListener(v->confirmDeleteClient(c));body.addView(del,new LinearLayout.LayoutParams(-1,dp(54)));
    }
    private View infoLine(String a,String b){LinearLayout r=new LinearLayout(this);r.setPadding(0,dp(5),0,dp(5));r.addView(text(a,12,MUTED,false),new LinearLayout.LayoutParams(0,-2,.35f));r.addView(text(b,13,INK,true),new LinearLayout.LayoutParams(0,-2,.65f));return r;}
    private View emptyCard(String s){LinearLayout c=card();TextView t=text(s,13,MUTED,false);t.setGravity(Gravity.CENTER);t.setPadding(0,dp(14),0,dp(14));c.addView(t);return c;}
    private View filingCard(long clientId,DBHelper.Filing f){LinearLayout c=card();LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(text(f.month+" "+f.year,16,INK,true));tx.addView(text(safe(f.type)+" • Due "+safe(f.due),12,MUTED,false));r.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView st=text(f.status,11,statusColor(f.status),true);st.setPadding(dp(10),dp(6),dp(10),dp(6));st.setBackground(shape(statusBg(f.status),15));r.addView(st);c.addView(r);if(!"Filed".equals(f.status)&&!"Completed".equals(f.status)){Button done=pill("Mark Filed",R.drawable.ic_doc,false);done.setOnClickListener(v->{db.setFilingStatus(f.id,"Filed");clientProfile(clientId);});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(46));p.setMargins(0,dp(12),0,0);c.addView(done,p);}return c;}

    private void clientForm(DBHelper.Client c){final boolean edit=c!=null;ScrollView sv=new ScrollView(this);LinearLayout f=formWrap();EditText name=field(f,"Client Name",edit?c.name:"");EditText wa=field(f,"WhatsApp (+92...)",edit?c.whatsapp:"");EditText phone=field(f,"Phone",edit?c.phone:"");EditText cnic=field(f,"CNIC",edit?c.cnic:"");EditText ntn=field(f,"NTN",edit?c.ntn:"");EditText business=field(f,"Business / Company",edit?c.business:"");EditText type=field(f,"Tax Type (Income / Sales / Both)",edit?c.taxType:"");EditText due=field(f,"Next Due Date",edit?c.nextDue:"");EditText email=field(f,"Email",edit?c.email:"");EditText address=field(f,"Address",edit?c.address:"");EditText notes=field(f,"Notes",edit?c.notes:"");sv.addView(f);new AlertDialog.Builder(this).setTitle(edit?"Edit Client":"Add Client").setView(sv).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{if(name.getText().toString().trim().isEmpty()){toast("Client name required");return;}long id=db.saveClient(edit?c.id:0,val(name),val(wa),val(phone),val(cnic),val(ntn),val(business),val(type),"Active",val(due),val(email),val(address),val(notes));clientProfile(id);}).show();}
    private LinearLayout formWrap(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(18),dp(6),dp(18),dp(6));return f;}
    private EditText field(LinearLayout p,String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(safe(value).equals("—")?"":safe(value));e.setTextSize(14);e.setSingleLine(!hint.equals("Notes")&&!hint.equals("Address"));e.setPadding(dp(12),0,dp(12),0);e.setBackground(stroke(Color.WHITE,15,LINE));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp((hint.equals("Notes")||hint.equals("Address"))?74:52));lp.setMargins(0,0,0,dp(10));p.addView(e,lp);return e;}
    private String val(EditText e){return e.getText().toString().trim();}

    private void filingForm(long clientId){LinearLayout f=formWrap();EditText month=field(f,"Month (e.g. September)","");EditText year=field(f,"Year","2026");year.setInputType(InputType.TYPE_CLASS_NUMBER);EditText type=field(f,"Filing Type","Income Tax");EditText due=field(f,"Due Date","30 Sep 2026");EditText notes=field(f,"Notes","");new AlertDialog.Builder(this).setTitle("Add Filing").setView(f).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{int y=2026;try{y=Integer.parseInt(val(year));}catch(Exception ignored){}db.addFiling(clientId,val(month),y,val(type),val(due),"Pending",val(notes));clientProfile(clientId);}).show();}

    private void showReminders(){active="reminders";shell("Reminders","Local alerts + WhatsApp follow-up");LinearLayout hero=card();hero.setBackground(gradient(Color.rgb(124,185,255),BLUE,26));hero.addView(text("Scheduled reminders",13,Color.WHITE,false));hero.addView(text(db.countReminders()+" active",27,Color.WHITE,true));hero.addView(text("App notification can work without paid API.",12,0xFFE8F4FF,false));body.addView(hero);Button add=pill("Create Reminder",R.drawable.ic_add,true);add.setOnClickListener(v->reminderForm(0));body.addView(add,new LinearLayout.LayoutParams(-1,dp(56)));body.addView(title("Reminder queue"));List<DBHelper.Reminder> rs=db.reminders(0);if(rs.isEmpty())body.addView(emptyCard("No reminders scheduled."));for(DBHelper.Reminder r:rs)body.addView(reminderCard(r));body.addView(title("Quick test"));Button test=pill("Test Notification in 10 Seconds",R.drawable.ic_bell,false);test.setOnClickListener(v->scheduleLocal("Test FBR Reminder","This is a local reminder test.",System.currentTimeMillis()+10000));body.addView(test,new LinearLayout.LayoutParams(-1,dp(54)));}
    private View reminderCard(DBHelper.Reminder r){LinearLayout c=card();LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(text(r.title,15,INK,true));tx.addView(text((r.client==null?"General":r.client)+" • "+r.repeat+" • "+r.channel,11,MUTED,false));h.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView st=text(r.status,11,GREEN,true);h.addView(st);c.addView(h);c.addView(text(new SimpleDateFormat("dd MMM yyyy, hh:mm a",Locale.US).format(new Date(r.at)),12,BLUE2,true));Button del=pill("Remove",R.drawable.ic_bell,false);del.setTextColor(RED);del.setOnClickListener(v->{db.deleteReminder(r.id);showReminders();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(44));p.setMargins(0,dp(8),0,0);c.addView(del,p);return c;}
    private void reminderForm(long clientId){List<DBHelper.Client> clients=db.clients("");LinearLayout f=formWrap();Spinner sp=new Spinner(this);ArrayList<String> names=new ArrayList<>();names.add("General reminder");int selected=0;for(int i=0;i<clients.size();i++){names.add(clients.get(i).name);if(clients.get(i).id==clientId)selected=i+1;}sp.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));sp.setSelection(selected);f.addView(sp,new LinearLayout.LayoutParams(-1,dp(54)));EditText title=field(f,"Reminder title","FBR Return Reminder");EditText msg=field(f,"Message","Kindly apne required FBR / property return documents provide kar dein.");EditText mins=field(f,"Remind after minutes","1");mins.setInputType(InputType.TYPE_CLASS_NUMBER);EditText repeat=field(f,"Repeat (Once / Monthly)","Monthly");new AlertDialog.Builder(this).setTitle("New Reminder").setView(f).setNegativeButton("Cancel",null).setPositiveButton("Schedule",(d,w)->{long cid=0;if(sp.getSelectedItemPosition()>0)cid=clients.get(sp.getSelectedItemPosition()-1).id;int m=1;try{m=Integer.parseInt(val(mins));}catch(Exception ignored){}long at=System.currentTimeMillis()+m*60000L;db.addReminder(cid,val(title),val(msg),at,val(repeat),"Local + WhatsApp");scheduleLocal(val(title),val(msg),at);showReminders();}).show();}
    private void scheduleLocal(String title,String msg,long at){Intent i=new Intent(this,ReminderReceiver.class);i.putExtra("title",title);i.putExtra("message",msg);PendingIntent pi=PendingIntent.getBroadcast(this,(int)(System.currentTimeMillis()%1000000),i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE);try{if(android.os.Build.VERSION.SDK_INT>=31&&!am.canScheduleExactAlarms()){am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);}else am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);}catch(Exception e){am.set(AlarmManager.RTC_WAKEUP,at,pi);}toast("Reminder scheduled");}
    private void showClientReminders(long id){active="reminders";shell("Client Reminders","Follow-up history and schedule");Button add=pill("Add Reminder",R.drawable.ic_add,true);add.setOnClickListener(v->reminderForm(id));body.addView(add,new LinearLayout.LayoutParams(-1,dp(55)));body.addView(gap(10));List<DBHelper.Reminder> rs=db.reminders(id);if(rs.isEmpty())body.addView(emptyCard("No reminders for this client."));for(DBHelper.Reminder r:rs)body.addView(reminderCard(r));}

    private void showFilingsHub(){active="more";shell("FBR Filings","Open a client to manage monthly records");for(DBHelper.Client c:db.clients("")){LinearLayout x=card();x.addView(text(c.name,16,INK,true));x.addView(text(db.filings(c.id).size()+" filing records • "+safe(c.taxType),12,MUTED,false));x.setOnClickListener(v->clientProfile(c.id));body.addView(x);}}
    private void showCalendar(){active="more";shell("Due Calendar","Upcoming client dates");body.addView(title("Upcoming deadlines"));for(DBHelper.Client c:db.clients("")){LinearLayout x=card();x.setOrientation(LinearLayout.HORIZONTAL);TextView d=text(safe(c.nextDue),12,BLUE2,true);d.setGravity(Gravity.CENTER);d.setBackground(shape(Color.rgb(235,244,255),18));x.addView(d,new LinearLayout.LayoutParams(dp(108),dp(48)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(12),0,0,0);tx.addView(text(c.name,15,INK,true));tx.addView(text(safe(c.taxType),12,MUTED,false));x.addView(tx,new LinearLayout.LayoutParams(0,-2,1));x.setOnClickListener(v->clientProfile(c.id));body.addView(x);}}

    private void showDocuments(long clientId){DBHelper.Client c=db.client(clientId);active="more";shell("Documents",c==null?"Client records":c.name);Button add=pill("Add Document Record",R.drawable.ic_add,true);add.setOnClickListener(v->documentForm(clientId));body.addView(add,new LinearLayout.LayoutParams(-1,dp(55)));body.addView(gap(10));List<DBHelper.Document> ds=db.documents(clientId);if(ds.isEmpty())body.addView(emptyCard("No document record yet."));for(DBHelper.Document d:ds){LinearLayout x=card();x.addView(iconText(d.title,R.drawable.ic_doc,15,INK));x.addView(text(d.category+" • "+d.status,12,MUTED,false));if(d.notes!=null&&!d.notes.isEmpty())x.addView(text(d.notes,12,INK,false));body.addView(x);}}
    private void documentForm(long id){LinearLayout f=formWrap();EditText t=field(f,"Document title","Bank Statement");EditText cat=field(f,"Category","FBR Documents");EditText st=field(f,"Status","Required");EditText notes=field(f,"Notes","");new AlertDialog.Builder(this).setTitle("Document Record").setView(f).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{db.addDocument(id,val(t),val(cat),val(st),val(notes));showDocuments(id);}).show();}

    private void showPaymentsHub(){active="more";shell("Payments","Open client payment ledger");for(DBHelper.Client c:db.clients("")){LinearLayout x=card();x.addView(text(c.name,16,INK,true));x.addView(text(db.payments(c.id).size()+" payment records",12,MUTED,false));x.setOnClickListener(v->showPayments(c.id));body.addView(x);}}
    private void showPayments(long id){DBHelper.Client c=db.client(id);active="more";shell("Payments",c==null?"Client ledger":c.name);Button add=pill("Add Payment",R.drawable.ic_add,true);add.setOnClickListener(v->paymentForm(id));body.addView(add,new LinearLayout.LayoutParams(-1,dp(55)));body.addView(gap(10));List<DBHelper.Payment> ps=db.payments(id);if(ps.isEmpty())body.addView(emptyCard("No payment records."));for(DBHelper.Payment p:ps){LinearLayout x=card();LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(text(p.title,15,INK,true));tx.addView(text("Due "+safe(p.due)+" • "+p.status,12,MUTED,false));r.addView(tx,new LinearLayout.LayoutParams(0,-2,1));r.addView(text("Rs. "+String.format(Locale.US,"%.0f",p.amount),15,BLUE2,true));x.addView(r);body.addView(x);}}
    private void paymentForm(long id){LinearLayout f=formWrap();EditText t=field(f,"Service / Payment title","Monthly Consultancy");EditText a=field(f,"Amount","5000");a.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText due=field(f,"Due Date","10 Oct 2026");EditText st=field(f,"Status","Pending");EditText n=field(f,"Notes","");new AlertDialog.Builder(this).setTitle("Add Payment").setView(f).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{double amt=0;try{amt=Double.parseDouble(val(a));}catch(Exception ignored){}db.addPayment(id,val(t),amt,val(due),val(st),val(n));showPayments(id);}).show();}

    private void showReports(){active="more";shell("Reports","Live data from local ERP database");LinearLayout hero=card();hero.setBackground(gradient(Color.rgb(234,243,255),Color.WHITE,26));hero.addView(text("Business Snapshot",13,MUTED,true));hero.addView(text(db.countClients()+" total clients",28,INK,true));hero.addView(text(db.countPending()+" pending filings • "+db.countFiled()+" filed",13,BLUE2,true));body.addView(hero);body.addView(title("Performance"));reportRow("Client records",db.countClients(),Math.max(1,db.countClients()),BLUE);reportRow("Pending filings",db.countPending(),Math.max(1,db.countPending()+db.countFiled()),ORANGE);reportRow("Filed / completed",db.countFiled(),Math.max(1,db.countPending()+db.countFiled()),GREEN);reportRow("Scheduled reminders",db.countReminders(),Math.max(1,db.countClients()*2),BLUE2);}
    private void reportRow(String name,int val,int total,int color){LinearLayout c=card();c.addView(text(name,14,INK,true));c.addView(text(val+"",24,color,true));ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(total);p.setProgress(val);c.addView(p,new LinearLayout.LayoutParams(-1,dp(8)));body.addView(c);}

    private void showClientNotes(DBHelper.Client c){active="more";shell("Client Notes",c.name);LinearLayout box=card();box.addView(text("Email",12,MUTED,true));box.addView(text(safe(c.email),14,INK,false));box.addView(gap(10));box.addView(text("Address",12,MUTED,true));box.addView(text(safe(c.address),14,INK,false));box.addView(gap(10));box.addView(text("Notes",12,MUTED,true));box.addView(text(safe(c.notes),14,INK,false));body.addView(box);Button edit=pill("Edit Client",R.drawable.ic_edit,true);edit.setOnClickListener(v->clientForm(c));body.addView(edit,new LinearLayout.LayoutParams(-1,dp(55)));}

    private void showMore(){active="more";shell("More","ERP modules & settings");quickRow(body,"FBR Filings","All clients and filing history",R.drawable.ic_doc,()->showFilingsHub());quickRow(body,"Due Calendar","Monthly deadlines",R.drawable.ic_calendar,()->showCalendar());quickRow(body,"Documents","Open from each client profile",R.drawable.ic_doc,()->toast("Documents client profile ke andar available hain"));quickRow(body,"Payments","Fees and pending amounts",R.drawable.ic_payment,()->showPaymentsHub());quickRow(body,"Reports","Live dashboard reports",R.drawable.ic_grid,()->showReports());quickRow(body,"Backup & Restore","Export guidance",R.drawable.ic_settings,()->showBackup());quickRow(body,"Settings","App preferences",R.drawable.ic_settings,()->showSettings());LinearLayout about=card();about.addView(text("Muzamil Abbas Property Return Filer",16,INK,true));about.addView(text("Version 2.0 • Premium local-first ERP",12,MUTED,false));about.addView(text("Client data stays in this app's SQLite database. WhatsApp opens with a prepared message without a paid API.",12,INK,false));body.addView(about);}
    private void showBackup(){active="more";shell("Backup & Restore","Protect your local client data");LinearLayout c=card();c.addView(iconText("Local Database",R.drawable.ic_doc,16,INK));c.addView(text("All clients, filings, reminders, payments and document records are stored on this device.",13,MUTED,false));c.addView(gap(10));c.addView(text("Recommended: use Android device backup and periodically export reports/screenshots until full file-export is enabled in the next build.",12,INK,false));body.addView(c);}
    private void showSettings(){active="more";shell("Settings","App preferences");LinearLayout c=card();c.addView(text("Brand",12,MUTED,true));c.addView(text("Muzamil Abbas Property Return Filer",16,INK,true));c.addView(gap(12));c.addView(text("Default reminder channel",12,MUTED,true));c.addView(text("Local Notification + One-tap WhatsApp",14,INK,false));c.addView(gap(12));c.addView(text("Storage",12,MUTED,true));c.addView(text("Private SQLite on device",14,INK,false));body.addView(c);Button perm=pill("Reminder Permission",R.drawable.ic_bell,true);perm.setOnClickListener(v->{if(android.os.Build.VERSION.SDK_INT>=31)startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM));});body.addView(perm,new LinearLayout.LayoutParams(-1,dp(54)));}

    private void openWhatsApp(DBHelper.Client c){try{String num=safe(c.whatsapp).replaceAll("[^0-9]","");String msg="Assalam o Alaikum "+c.name+", aap ka FBR / Property Return follow-up hai. Next due date: "+safe(c.nextDue)+". Kindly required documents provide kar dein. Regards, Muzamil Abbas Property Return Filer";startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://wa.me/"+num+"?text="+URLEncoder.encode(msg,"UTF-8"))));}catch(Exception e){toast("WhatsApp open nahi ho saka");}}
    private void confirmDeleteClient(DBHelper.Client c){new AlertDialog.Builder(this).setTitle("Delete "+c.name+"?").setMessage("Is client ke filings, reminders, documents aur payment records bhi delete honge.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{db.deleteClient(c.id);showClients("");}).show();}

    private int statusColor(String s){if("Filed".equals(s)||"Completed".equals(s))return GREEN;if("Waiting Documents".equals(s))return ORANGE;return RED;}
    private int statusBg(String s){if("Filed".equals(s)||"Completed".equals(s))return Color.rgb(232,248,239);if("Waiting Documents".equals(s))return Color.rgb(255,247,226);return Color.rgb(255,235,235);}
    private String safe(String s){return s==null||s.trim().isEmpty()?"—":s;}
    private String initials(String s){if(s==null||s.trim().isEmpty())return "C";String[] p=s.trim().split("\\s+");return p.length>1?(p[0].substring(0,1)+p[1].substring(0,1)).toUpperCase():p[0].substring(0,1).toUpperCase();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}