package com.muzamil.propertyreturnfiler;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.Bundle;import android.view.*;import android.widget.*;import java.net.URLEncoder;

public class MainActivity extends Activity{
 int P=Color.rgb(27,20,243),I=Color.rgb(8,7,25),B=Color.rgb(251,251,253),M=Color.rgb(137,132,180);LinearLayout root,body;
 int dp(int v){return(int)(v*getResources().getDisplayMetrics().density);}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(null,b?Typeface.BOLD:Typeface.NORMAL);v.setPadding(0,dp(4),0,dp(4));return v;}
 LinearLayout card(int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(18),dp(16),dp(18),dp(16));x.setBackground(bg(c,24));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));x.setLayoutParams(p);return x;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(I);b.setBackground(bg(0xFFE9E8FF,18));return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);new DBHelper(this).getWritableDatabase();if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7);home();}
 void shell(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(10));root.setBackgroundColor(B);root.addView(t("Muzamil Abbas",14,M,true));root.addView(t(title,28,I,true));ScrollView s=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,dp(14),0,dp(60));s.addView(body);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);String[] n={"Home","Clients","Reminders","More"};for(String q:n){Button x=btn(q);x.setBackgroundColor(Color.TRANSPARENT);x.setOnClickListener(v->{if(q.equals("Home"))home();else if(q.equals("Clients"))clients();else if(q.equals("Reminders"))reminders();else more();});nav.addView(x,new LinearLayout.LayoutParams(0,dp(52),1));}root.addView(nav);setContentView(root);}
 void home(){shell("Property Return Filer");LinearLayout h=card(P);h.addView(t("Good evening 👋",15,Color.WHITE,false));h.addView(t("Your FBR work, under control.",25,Color.WHITE,true));h.addView(t("Local data • Smart reminders • One-tap WhatsApp",14,0xFFE0DFFF,false));body.addView(h);LinearLayout r=new LinearLayout(this);r.addView(stat("3","Clients"),new LinearLayout.LayoutParams(0,dp(115),1));Space sp=new Space(this);r.addView(sp,new LinearLayout.LayoutParams(dp(10),1));r.addView(stat("3","Pending"),new LinearLayout.LayoutParams(0,dp(115),1));body.addView(r);body.addView(t("Upcoming deadlines",18,I,true));deadline("Ali Traders","Sales Tax","30 Aug 2026");deadline("Khan Property Solutions","Income Tax","15 Sep 2026");deadline("Muzamil Estate Services","Both","30 Sep 2026");}
 View stat(String a,String b){LinearLayout c=card(Color.WHITE);c.addView(t(a,28,I,true));c.addView(t(b,14,M,false));return c;}
 void deadline(String a,String b,String c){LinearLayout x=card(Color.WHITE);x.addView(t(a,17,I,true));x.addView(t(b+" • Due "+c,13,M,false));body.addView(x);}
 void clients(){shell("Clients");String[][] d={{"Ali Traders","+923001234567","Sales Tax","30 Aug 2026"},{"Khan Property Solutions","+923117654321","Income Tax","15 Sep 2026"},{"Muzamil Estate Services","+923221112233","Both","30 Sep 2026"}};for(String[] c:d){LinearLayout x=card(Color.WHITE);x.addView(t(c[0],18,I,true));x.addView(t(c[2]+" • "+c[3],13,M,false));Button w=btn("WhatsApp reminder");w.setOnClickListener(v->wa(c[1],c[0],c[3]));x.addView(w);body.addView(x);}}
 void wa(String no,String name,String due){try{String m="Assalam o Alaikum "+name+", aap ka FBR / Property Return reminder due hai. Next due date: "+due+". Kindly required documents provide kar dein. Regards, Muzamil Abbas Property Return Filer";startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+no.replace("+","")+"?text="+URLEncoder.encode(m,"UTF-8"))));}catch(Exception e){Toast.makeText(this,"WhatsApp open nahi ho saka",Toast.LENGTH_SHORT).show();}}
 void reminders(){shell("Reminders");LinearLayout h=card(P);h.addView(t("Today",14,0xFFE0DFFF,false));h.addView(t("3 reminders scheduled",24,Color.WHITE,true));body.addView(h);Button b=btn("Test reminder in 10 seconds");b.setOnClickListener(v->alarm());body.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));String[] r={"7 days before due date","3 days before due date","1 day before due date","On due date","Custom monthly reminder"};for(String s:r){LinearLayout x=card(Color.WHITE);x.addView(t(s,16,I,true));x.addView(t("Enabled",13,0xFF1E9E63,true));body.addView(x);}}
 void alarm(){Intent i=new Intent(this,ReminderReceiver.class);PendingIntent p=PendingIntent.getBroadcast(this,9,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager a=(AlarmManager)getSystemService(ALARM_SERVICE);a.set(AlarmManager.RTC_WAKEUP,System.currentTimeMillis()+10000,p);Toast.makeText(this,"Reminder scheduled",Toast.LENGTH_SHORT).show();}
 void more(){shell("More");String[] x={"FBR Filings","Calendar","Documents","Payments","Reports","Backup & Restore","Settings","About"};for(String s:x){Button b=btn(s);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,0,0,dp(9));body.addView(b,p);}LinearLayout c=card(Color.WHITE);c.addView(t("Muzamil Abbas Property Return Filer",17,I,true));c.addView(t("v1.0.0 • Offline-first Android ERP",13,M,false));c.addView(t("SQLite local data + local reminders + free one-tap WhatsApp.",13,I,false));body.addView(c);}
}